Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISDProject.Models;
using ISDProject.Filters;
using PagedList;
using System.IO;
using ISDProject.Tools;
using BootstrapMvcSample.Controllers;

namespace ISDProject.Controllers
{

    public class DocumentController : BootstrapBaseController
    {
        private ISDProjectContext context = new ISDProjectContext();

        //
        // GET: /Document/

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var doc_user = User.Identity.Name;
            //
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Link_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //
            var objects = context.Document.Include(objectmodels => objectmodels.Comments);

            if (!String.IsNullOrEmpty(searchString))
            {
                objects = objects.Where(s => s.DocumentName.ToUpper().Contains(searchString.ToUpper())
                                       || s.DocumentName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Link_desc":
                    objects = objects.OrderByDescending(s => s.DocumentName);
                    break;
                case "Date":
                    objects = objects.OrderBy(s => s.DocumentCreation);
                    break;
                case "Date_desc":
                    objects = objects.OrderByDescending(s => s.DocumentCreation);
                    break;
                default:
                    objects = objects.OrderBy(s => s.DocumentName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(objects.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Document/Details/5

        public ViewResult Details(int id)
        {
            var doc_user = User.Identity.Name;
            Document document = context.Document.Single(x => x.DocumentId == id);
            document.Comments = document.Comments.OrderBy(x => x.CommentCreation).ToList();
            Comment comment = new Comment();
            comment.DocumentId = document.DocumentId;
            comment.CommentUserName = doc_user;
            DocumentComment doc_com = new DocumentComment()
            {
                Comment = comment,
                Document = document
            };
            return View(doc_com);
        }

        //
        // GET: /Document/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Document/Create

        [HttpPost]
        public ActionResult Create(IEnumerable<HttpPostedFileBase> files)
        {
            var doc_user = User.Identity.Name;
            // Fichiers joints
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var doc_name = Path.GetFileName(file.FileName);
                    String dir = AppDomain.CurrentDomain.BaseDirectory + doc_user;
                    var doc_path = Path.Combine(dir, doc_name);
                    //
                    if (!System.IO.Directory.Exists(dir))
                        System.IO.Directory.CreateDirectory(dir);
                    //

                    file.SaveAs(doc_path);
                    int doc_size = Tools.Tools.GetFileSize(doc_path);
                    DateTime now = DateTime.Now;
                    //
                    Document document = new Document()
                    {
                         DocumentName = doc_name,
                         DocumentPath = doc_path,
                         DocumentSize = doc_size,
                         DocumentUser = doc_user,
                         DocumentCreation = now,
                         DocumentModification = now
                    };
                    context.Document.Add(document);
                }
            }
            context.SaveChanges();
            Success("Your document is uploaded successfully !");
            return RedirectToAction("Index");
        }

        //
        // GET: /Document/Edit/5

        public ActionResult Edit(int id)
        {
            Document document = context.Document.Single(x => x.DocumentId == id);
            return View(document);
        }

        //
        // POST: /Document/Edit/5

        [HttpPost]
        public ActionResult Edit(Document document)
        {
            if (ModelState.IsValid)
            {
                context.Entry(document).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(document);
        }

        //
        // GET: /Document/Delete/5

        public ActionResult Delete(int id)
        {
            Document document = context.Document.Single(x => x.DocumentId == id);
            Tools.Tools.DeleteFile(document.DocumentPath);
            context.Document.Remove(document);
            context.SaveChanges();
            //

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ShareLink(String link, String email, String message, String file)
        {
            var doc_user = User.Identity.Name;
            Tools.Tools.SendMessage(email, doc_user, message, link, file);
            Success("Mail sended successfully !");
            return RedirectToAction("Index");
        }

        public ActionResult AddComment(DocumentComment doc_com)
        {
            DateTime now = DateTime.Now;
            doc_com.Comment.CommentCreation = now;
            doc_com.Comment.CommentModification = now;
            if (ModelState.IsValid)
            {
                context.Comment.Add(doc_com.Comment);

                context.SaveChanges();

                doc_com.Document = doc_com.Document;
                doc_com.Document.DocumentRate = doc_com.Document.DocumentRate + doc_com.Comment.CommentRate;
                doc_com.Document.DocumentModification = now;
                context.Entry(doc_com.Document).State = EntityState.Modified;
                context.SaveChanges();
            }
            Document document = context.Document.Include(x => x.Comments).Single(x => x.DocumentId == doc_com.Comment.DocumentId);
            Success("Comment added successfully !");
            return PartialView("_ListComments", document.Comments);
        }

        public void Capture()
        {
            var stream = Request.InputStream;
            string dump;

            using (var reader = new StreamReader(stream))
                dump = reader.ReadToEnd();

            var path = Server.MapPath("~/test.jpg");
            System.IO.File.WriteAllBytes(path, String_To_Bytes2(dump));
        }

        private byte[] String_To_Bytes2(string strInput)
        {
            int numBytes = (strInput.Length) / 2;
            byte[] bytes = new byte[numBytes];

            for (int x = 0; x < numBytes; ++x)
            {
                bytes[x] = Convert.ToByte(strInput.Substring(x * 2, 2), 16);
            }

            return bytes;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISDProject.Controllers
{
    public class FileController : Controller
    {
        /// <summary>
        /// Récupérer le document stocké dans le serveur
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public FileResult Download(string fileName)
        {
            FileResult res = null;
            byte[] fileBytes = GetFile(fileName);
            try
            {
                res = File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(fileName));
            }
            catch (Exception e)
            {

            }
            return res;
        }

        /// <summary>
        /// Convertit un fichier en tableau de byte
        /// </summary>
        /// <param name="s"></param>
        /// <returns></returns>
        public byte[] GetFile(string s)
        {
            byte[] data = null;
            System.IO.FileStream fs = null;
            try
            {
                fs = System.IO.File.OpenRead(s);
                data = new byte[fs.Length];
                int br = fs.Read(data, 0, data.Length);
                if (br != fs.Length)
                    throw new System.IO.IOException(s);
            }
            catch (Exception e)
            {
            }
            finally
            {
                if (fs != null)
                {
                    fs.Close();
                }
            }
            return data;
        }
    }
}

Views/Document/Create.cshtml
@model ISDProject.Models.Document

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Document</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



Views/Document/Delete.cshtml
@model ISDProject.Models.Document

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Document</legend>

    <div class="display-label">DocumentName</div>
    <div class="display-field">@Model.DocumentName</div>

    <div class="display-label">DocumentPath</div>
    <div class="display-field">@Model.DocumentPath</div>

    <div class="display-label">DocumentSize</div>
    <div class="display-field">@Model.DocumentSize</div>

    <div class="display-label">DocumentRate</div>
    <div class="display-field">@Model.DocumentRate</div>

    <div class="display-label">DocumentUser</div>
    <div class="display-field">@Model.DocumentUser</div>

    <div class="display-label">DocumentCreation</div>
    <div class="display-field">@String.Format("{0:g}", Model.DocumentCreation)</div>

    <div class="display-label">DocumentModification</div>
    <div class="display-field">@String.Format("{0:g}", Model.DocumentModification)</div>

    <div class="display-label">Comments</div>
    <div class="display-field">@(Model.Comments == null ? "None" : Model.Comments.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}



Views/Document/Details.cshtml
@model ISDProject.Models.DocumentComment
@using ISDProject.Tools

@{
    ViewBag.Title = "Details";
}
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/chili-1.7.pack.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.media.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.metadata.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(function () {
            $('.media').media({
                width: "100%",
                height: 600
            });
        });
    </script>
}
<header class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>Preview</h1>
        <p class="lead">
            <a href="../"><img src="~/Content/images/left_round.png" style="height: 40px; width : 40px" /></a> @Model.Document.DocumentName
             @Html.ActionLink("Download", "Download", "File", new { fileName = Model.Document.DocumentPath }, new { @class = "btn" })
            <a class="btn btn-primary" href="#modal_share_link" data-dismiss="modal" data-toggle="modal" onclick="document.getElementById('link').value='@(_link)';document.getElementById('file').value='@item.DocumentName';">Share</a>
        </p>
        <p class="muted">@String.Format("{0:g}", Model.Document.DocumentCreation) - @Tools.GetFileSizeString(Model.Document.DocumentSize) - @Model.Document.DocumentUser</p>
    </div>
</header>

@{
    HttpContext _context = HttpContext.Current;
    String _baseUrl = _context.Request.Url.Scheme + "://" + _context.Request.Url.Authority + _context.Request.ApplicationPath.TrimEnd('/') + '/';
    String _path = Model.Document.DocumentPath.Replace("\\", "\\\\");
    String _link = _baseUrl + "File/Download?fileName=" + _path;
}

<div class="well">
    <div>
        <a class="media" href="@_link" style="width: 100%; height: 500px"></a>
    </div>
</div>

<div id="commentsList">
    @{ Html.RenderPartial("_ListComments", Model.Document.Comments); }
</div>


@using (Ajax.BeginForm("AddComment", new AjaxOptions { UpdateTargetId = "commentsList", OnSuccess = "$('#form0').get(0).reset();" }))
{
    @Html.HiddenFor(model => model.Comment.DocumentId)
    @Html.HiddenFor(model => model.Comment.CommentUserName)
    //
    @Html.HiddenFor(model => model.Document.DocumentId);
    @Html.HiddenFor(model => model.Document.DocumentName)

    @Html.HiddenFor(model => model.Document.DocumentPath)

    @Html.HiddenFor(model => model.Document.DocumentSize)

    @Html.HiddenFor(model => model.Document.DocumentRate)

    @Html.HiddenFor(model => model.Document.DocumentUser)

    @Html.HiddenFor(model => model.Document.DocumentCreation)

    @Html.HiddenFor(model => model.Document.DocumentModification)
    //

    <div class="row-fluid">
        <div class="span12">
            @Html.TextAreaFor(x => x.Comment.CommentValue, new { placeholder = "Join the discussion", @class = "input-block-level", style = "margin:0px" })
        </div>
    </div>
    <br />
    var items = new List<SelectListItem>{
        new SelectListItem {Value = "1", Text = "1"},
        new SelectListItem {Value = "2", Text = "2"},
        new SelectListItem {Value = "3", Text = "3"},
        new SelectListItem {Value = "4", Text = "4"},
        new SelectListItem {Value = "5", Text = "5"}
    };

    @Html.DropDownListFor(x => x.Comment.CommentRate, items)

    <br />
    <div class="row-fluid">
        <div class="span12">
            <input class="btn btn-primary" type="submit" value="Add Comment" />
            <button class="btn" onclick="$('#form0').get(0).reset();" type="button">Clear</button>
        </div>
    </div>
}




Views/Document/Edit.cshtml
@model ISDProject.Models.Document

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Document</legend>

        @Html.HiddenFor(model => model.DocumentId)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Document/Index.cshtml
@model PagedList.IPagedList<ISDProject.Models.Document>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

@section Scripts{
    <script src="@Url.Content("~/Scripts/jquery.webcam.js")"></script>
    <script>
        function deleteDocument(id, file) {
            $('#objet_a_supprimer').html(file);
            $('#boutonConfirmation').click(function () {
                window.location.href = '@Url.Action("Delete/")' + id;
            });
            $('#modal_confirmation_suppression').modal('show');
        }

    </script>
    <script>
        $("#Camera").webcam({
            width: 400,
            height: 300,
            mode: "save",
            swffile: "@Url.Content("~/Content/tool/jscam.swf")",
            onTick: function () { },
            onSave: function () {
            },
            onCapture: function () {
                webcam.save("@Url.Content("~/App_Data/uploads")/");
            },
            debug: function () { },
            onLoad: function () { }
        });
    </script>
    <script type="text/javascript">
        $('#myTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        });
    </script>
}


<header class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>Documents</h1>
        <p class="lead">Upload. Share. Enjoy.</p>
    </div>
</header>

<div class="row-fluid">
    <div class="span4">
        <a class="btn btn-primary" href="#modal_add_new" data-dismiss="modal" data-toggle="modal">Add New</a>
    </div>
    <div class="span4 offset4">
        @using (Html.BeginForm("Index", "Document", FormMethod.Get, new { @class = "form-search" }))
        {
            <div class="input-append">
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "span12 search-query", type = "text" })
                <button type="submit" class="btn">Search</button>
            </div>
        }
    </div>
</div>

<table class="table table-striped">
    <tr>
        <th style="width: 35%">
            @Html.ActionLink("Document Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>Kind
        </th>
        <th>Rate
        </th>
        <th>Size
        </th>
        <th>Created
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.DocumentName
            </td>
            <td>
                @Path.GetExtension(item.DocumentName)
            </td>
            <td>
                @{
        float rate = item.DocumentRate;
        int count = (item.Comments.Count == 0) ? 1 : item.Comments.Count;
        int _rating = (int) rate / count;
                    }
                            @{
                int starOff = 5 - _rating;
                for (int i = 0; i < (int)_rating; i++)
        {
                <img src="~/Content/images/star-on.png" />
        }
                for (int i = 0; i < starOff; i++)
        {
                <img src="~/Content/images/star-off.png" />
        }
            }
               (@item.Comments.Count())
            </td>
            <td>
                @item.DocumentSize
            </td>
            <td>
                @String.Format("{0:g}", item.DocumentCreation)
            </td>
            <td>
                @{
        HttpContext _context = HttpContext.Current;
        String _baseUrl = _context.Request.Url.Scheme + "://" + _context.Request.Url.Authority + _context.Request.ApplicationPath.TrimEnd('/') + '/';
        String _path = item.DocumentPath.Replace("\\", "\\\\");
        String _link = _baseUrl + "File/Download?fileName=" + _path;
                }
                @Html.ActionLink("Download", "Download", "File", new { fileName = item.DocumentPath }, new { @class = "btn" })
                <a class="btn btn-primary" href="#modal_share_link" data-dismiss="modal" data-toggle="modal" onclick="document.getElementById('link').value='@(_link)';document.getElementById('file').value='@item.DocumentName';">Share</a>
                @Html.ActionLink("Details", "Details", new { id = item.DocumentId }, new { @class = "btn btn-warning" })
                <a class="btn" onclick="deleteDocument(@(item.DocumentId), '@(item.DocumentName)');" title="Delete"><i class="icon-trash"></i></a>
            </td>
        </tr>
    }

</table>

<div class="row" style="text-align: center">
    <div class="span6" style="float: none; margin: 0 auto;">
        @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div>

<div id="modal_add_new" class="modal fade" style="display: none;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4>Upload Files</h4>
    </div>
    <div class="modal-body">
        <div class="row-fluid">

            <!-- Navigation Buttons -->
            <div class="span12">
                <ul class="nav nav-pills" id="myTabs">
                    <li class="active"><a href="#files">Files</a></li>
                    <li><a href="#camera">Camera</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="files">
                        <div class="alert alert-info">
                            File size limit : 8 Mo
                        </div>
                        @using (Html.BeginForm("Create", "Document", FormMethod.Post, new { enctype = "multipart/form-data", @id = "files_form" }))
                        {
                  
                            <input type="file" name="files" id="file1" /><br />
                            <input type="file" name="files" id="file2" /><br />
                            <input type="file" name="files" id="file3" /><br />
                            <input type="file" name="files" id="file4" /><br />
                            <input type="file" name="files" id="file5" />
                        }
                    </div>
                    <div class="tab-pane" id="camera">
                        <input type="button" value="Shoot!" onclick="webcam.capture();" />
                        <div id="Camera"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="controls">
            <button class="btn" data-dismiss="modal" data-toggle="modal">Cancel</button>
            <a class="btn btn-primary" onclick="$('#files_form').submit()">Upload</a>
        </div>
    </div>
</div>

<div id="modal_share_link" class="modal fade" style="display: none;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4>Share a Link</h4>
    </div>
    <div class="modal-body" style="max-height: 500px;">
        @using (Html.BeginForm("ShareLink", "Document", FormMethod.Post, new { @id = "share_form" }))
        {
            <div class="row-fluid control-group">
                <div class="controls">
                    <label for="file" class="control-label">File</label>
                    <input type="text" class="form-control span12" id="file" name="file" readonly />
                    <input type="text" class="form-control span12"
                        id="link" name="link" readonly />
                </div>
            </div> 
      
            <div class="row-fluid control-group">
                <div class="controls">
                    <label for="emails" class="control-label">Email</label>
                    <input type="email" class="form-control span12" placeholder="Email"
                        id="email" name="email" required
                        data-validation-required-message="Please enter your email" />
                </div>
            </div>         
                        
            <div class="row-fluid control-group">
                <div class="controls">
                    <label for="message" class="control-label">Message</label>
                    <textarea rows="4" cols="100" class="form-control span12"
                        placeholder="Message" id="message" name="message"
                        maxlength="999" style="resize: none"></textarea>
                </div>
            </div>                 
        }
    </div>
    <div class="modal-footer">
        <div class="controls">
            <button class="btn" data-dismiss="modal" data-toggle="modal">Cancel</button>
            <a class="btn btn-primary" onclick="$('#share_form').submit()">Share</a>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_confirmation_suppression" style="display: none;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4>Delete
        </h4>
    </div>
    <div class="modal-body">
        <!-- Debut Contenu MODAL -->
        <div class="row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <div class="span12">Do you really want to delete the file :</div>
                </div>
                <div class="row-fluid">
                    <div class="span12" id="objet_a_supprimer" style="font-weight: bold"></div>
                </div>
            </div>
        </div>
        <!--Contenu MODAL -->
    </div>
    <div class="modal-footer">
        <div class="controls">
            <button class="btn" data-dismiss="modal" data-toggle="modal">Cancel</button>
            <button type="submit" class="btn btn-danger" id="boutonConfirmation">
                <i class="icon-remove icon-white"></i>Delete
            </button>
        </div>
    </div>
</div>


Views/Document/_CreateOrEdit.cshtml
@model ISDProject.Models.Document

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentName)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentName)
    @Html.ValidationMessageFor(model => model.DocumentName)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentPath)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentPath)
    @Html.ValidationMessageFor(model => model.DocumentPath)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentSize)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentSize)
    @Html.ValidationMessageFor(model => model.DocumentSize)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentRate)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentRate)
    @Html.ValidationMessageFor(model => model.DocumentRate)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentUser)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentUser)
    @Html.ValidationMessageFor(model => model.DocumentUser)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentCreation)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentCreation)
    @Html.ValidationMessageFor(model => model.DocumentCreation)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.DocumentModification)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.DocumentModification)
    @Html.ValidationMessageFor(model => model.DocumentModification)
</div>


Views/Document/_ListComments.cshtml
@model IEnumerable<ISDProject.Models.Comment>
<fieldset>
    <legend>Comments (@(Model == null ? "0" : Model.Count().ToString()))</legend>
    @foreach (var item in Model)
    {
        <blockquote>
            <p>@item.CommentValue</p>
            @{
                int starOff = 5 - item.CommentRate;
        for (int i = 0; i < item.CommentRate; i++)
        {
                <img src="~/Content/images/star-on.png" />
        }
                for (int i = 0; i < starOff; i++)
        {
                <img src="~/Content/images/star-off.png" />
        }
            }
            <small>@item.CommentUserName <cite title="Source Title">@item.CommentCreation</cite></small>
        </blockquote> 
    }

</fieldset>